# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_success:
  - Rscript -e 'covr::codecov(line_exclusions = dir("src", pattern = "^readstat|CKHash", full.names = TRUE))'
