language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - Rcpp

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
